### ISSUE TITLE
Ruby on Rails update needed

### ISSUE THREAD

**Issue by travismetcalfe** [travismetcalfe/pale-blue-dot#1]
Our production server will soon be upgraded to Ubuntu 18.04

The application is currently running under Ruby 1.8.7 / Rails 2.3.15
We need to update the code to run under Ruby 2.4.6 / Rails 5.2.3

Please fork the code and implement the update. We will then deploy it on our 
development server to ensure that it runs properly under Ubuntu 18.04.

**Comment by willy2dg** [comment]
I am taking it a look

**Comment by travismetcalfe** [comment]
The development server is actually running Ruby 2.4.6 / Rails 5.2.3 so I have updated the issue description above.

**Comment by willy2dg** [comment]
Hi @travismetcalfe , i am trying to prepare the enviroment, but i am having some throuble to create the database since the migrate command is indexing a unexistent column ( const ) , could be the migration files deprecated ? The stars list ( KIC.txt ) and the importer ( import-stars.sql ) seems to be working in diferent formats too ( missed "const" field and diferent field positions ).

**Comment by travismetcalfe** [comment]
Sorry about the error -- we run the database on a separate server, so I did not notice that the version in the repository was out of date. I have just uploaded the current version!

**Comment by willy2dg** [comment]
Hi @travismetcalfe , no problem, can you check the scripts on "db/migrate", seems there still the problem adding unexistent index. Provably will be the "create_starts" script, but could be a lack of some file.

**Comment by travismetcalfe** [comment]
Hi @willy2dg , The create_stars script has been updated to reflect the current db. I hope it works for you now.

**Comment by willy2dg** [comment]
Yes @travismetcalfe , it is working now.

**Comment by willy2dg** [comment]
Hi @travismetcalfe , i have the aplication almost updated, just some little things to fix left. The default text encoding changed for Ruby and Rails, its ok if i convert the DB data to UTF-8 instead of doing some patch for that ?

**Comment by travismetcalfe** [comment]
Thanks, @willy2dg -- converting the DB data to UTF-8 should be ok.

**Comment by willy2dg** [comment]
@travismetcalfe i sent a working PR, you provably need to set the config.force_ssl to true on your enviroment to force https. I updated the README since some step changed slightly, tell me if there is some issue.

**Comment by travismetcalfe** [comment]
Thanks, @willy2dg -- I am installing this version on devel.adoptastar.org but I get the following error in the access log: "ActionView::Template::Error (The asset "scaffold.css" is not present in the asset pipeline.)" I am not sure why the system does not find it in /assets/stylesheets/.

**Comment by willy2dg** [comment]
Sorry @travismetcalfe i forget to run the production enviroment, i updated my PR and should work now.

**Comment by travismetcalfe** [comment]
Thanks @willy2dg -- I have updated the installation, but there is a new problem. Does this version require NodeJS on the server? I am getting errors: "allocation failure GC in old space requested" and "last resort GC in old space requested", which may be related to the server environment.

**Comment by willy2dg** [comment]
Yes, it is used to perform some tasks to the assets. Let me check how to disable this on production, should be enough serving the static files on production if you don't want to add some memory to node.

**Comment by travismetcalfe** [comment]
Thanks @willy2dg -- our hosting provider does not offer NodeJS without an upgrade in our subscription plan, so it would good to avoid using it if possible.

**Comment by willy2dg** [comment]
@travismetcalfe I pushed a update and should works now without NodeJs.

**Comment by travismetcalfe** [comment]
Thanks @willy2dg -- the stars application is now running at https://devel.adoptastar.org/  and the search functions appear to work. Hoever, click any "View Star" link to see that the individual star pages are not yet working. From the logs:
 Started GET "/stars/757076"
 Processing by StarsController#show as HTML
   Parameters: {"id"=>"757076"}
 Completed 500 Internal Server Error in 1ms (ActiveRecord: 0.0ms)
 ActiveRecord::UnknownPrimaryKey (Unknown primary key for table stars in model Star.)
 app/controllers/stars_controller.rb:18:in `show'

**Comment by travismetcalfe** [comment]
The database contains both "id" (integer), and "number" (string), where the string includes a prefix (KIC or EPIC). We use "id" to uniquely identify each star and display it in Google Sky.

**Comment by willy2dg** [comment]
@travismetcalfe seems strange since it was working on my enviroment, but i will take a look to fix it.

**Comment by willy2dg** [comment]
I am not sure if this update will solve the issue because i can not reproduce it, but i forced the "id" field on "star" to be the primary key. Also you said "id" is an integer on the DB, it should be a bigint, could you confirm this if the update does not work? Sorry for the inconveniences

**Comment by willy2dg** [comment]
@travismetcalfe seems there is some problem in the DB, searching from Aquarius consteltion shows incorrect characters too. Do you used the updated installation instructions and updated import-stars.sql ?

**Comment by travismetcalfe** [comment]
Many thanks, @willy2dg -- I was working with a copy of the old db. I updated the structure of the db manually (the "rails db:migrate" step did not work for me), and everything now seems to work. I have merged your fork into the master, and I will close this issue shortly so you can claim the bounty.

**Comment by willy2dg** [comment]
Thanks @travismetcalfe , i sent a bounty claim. The migrate comand should work on an empty DB, any ways i am able to check it if you want.

**Comment by travismetcalfe** [comment]
@willy2dg - new security defaults in rails4+ prevent the application from being displayed in an iframe, see https://stackoverflow.com/questions/16561066/ruby-on-rails-4-app-does-not-work-in-iframe

Can you please recommend how to apply this fix? I want to allow the application to be viewed in an iframe from adoptstar.org

Thanks!

**Comment by willy2dg** [comment]
Hi @travismetcalfe, right now i am not sure at all, but taking a quick look the solution seems to be adding the code bellow to `config / application.rb`, since `X-Frame-Options: ALLOW-FROM yoursite.com` is not supported for all browsers.

```
config.action_dispatch.default_headers = {
  'Access-Control-Allow-Origin' => 'https://adoptastar.org'
}
```
This is supposed to allow access to content from the specified external site. Tell me if it doesn't works to look it more in depth.

**Comment by travismetcalfe** [comment]
@willy2dg - yes, that seems to work. Thanks!

**Comment by travismetcalfe** [comment]
@willy2dg - I noticed one final issue before we can use this in production. On mobile devices with smaller screens, the css is designed to render the table below (rather than beside) the search form. This does not seem to work in the new code.

**Comment by willy2dg** [comment]
Sent a PR
